---
ID: "14595b3c-00f6-48f0-99ec-9b3eea237af1"
Parent: "16fc8179-86a7-4c9d-aa8b-7138bbf2bf8b"
Template: "16fc8179-86a7-4c9d-aa8b-7138bbf2bf8b"
Path: /sitecore/templates/Feature/ArticleTemplates/ArticleRenderingParameters/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "6141dfb1-b9f5-4ee1-babe-495a8d52825a"
